// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID         int32
	Source     string
	ExternalID string
	Title      string
	Link       string
	BudgetText string
	AmountMin  int64
	AmountMax  int64
	CreatedAt  pgtype.Timestamptz
}
