// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const createProjectIfNotExists = `-- name: CreateProjectIfNotExists :one
INSERT INTO projects (
  source,
  external_id,
  title,
  link,
  budget_text,
  amount_min,
  amount_max
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (source, external_id) DO NOTHING
RETURNING id, source, external_id, title, link, budget_text, amount_min, amount_max, created_at
`

type CreateProjectIfNotExistsParams struct {
	Source     string
	ExternalID string
	Title      string
	Link       string
	BudgetText string
	AmountMin  int64
	AmountMax  int64
}

func (q *Queries) CreateProjectIfNotExists(ctx context.Context, arg CreateProjectIfNotExistsParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProjectIfNotExists,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.Link,
		arg.BudgetText,
		arg.AmountMin,
		arg.AmountMax,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Link,
		&i.BudgetText,
		&i.AmountMin,
		&i.AmountMax,
		&i.CreatedAt,
	)
	return i, err
}

const getProjectBySourceExternalID = `-- name: GetProjectBySourceExternalID :one
SELECT id, source, external_id, title, link, budget_text, amount_min, amount_max, created_at
FROM projects
WHERE source = $1 AND external_id = $2
LIMIT 1
`

type GetProjectBySourceExternalIDParams struct {
	Source     string
	ExternalID string
}

func (q *Queries) GetProjectBySourceExternalID(ctx context.Context, arg GetProjectBySourceExternalIDParams) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectBySourceExternalID, arg.Source, arg.ExternalID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Link,
		&i.BudgetText,
		&i.AmountMin,
		&i.AmountMax,
		&i.CreatedAt,
	)
	return i, err
}
